//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tm_Tasks
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Category { get; set; }
        public string Assignee { get; set; }
    }
}
