//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StanovniciHrvatske
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventurniZapisi
    {
        public int Id { get; set; }
        public string Artikl { get; set; }
        public int Kolicina { get; set; }
        public int StvarnaKolicina { get; set; }
        public string Zaduzen { get; set; }
    }
}
