//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StanovniciHrvatske
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnici
    {
        public int Id { get; set; }
        public string ImePrezime { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int IdUloge { get; set; }
        public int IdOdjela { get; set; }
    
        public virtual Odjel Odjel { get; set; }
        public virtual Uloge Uloge { get; set; }
    }
}
