//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StanovniciHrvatske
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabsEntities : DbContext
    {
        public LabsEntities()
            : base("name=LabsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adrese> Adrese { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<InventurniZapisi> InventurniZapisis { get; set; }
        public virtual DbSet<Korisnici> Korisnicis { get; set; }
        public virtual DbSet<Mjesta> Mjestas { get; set; }
        public virtual DbSet<Odjel> Odjels { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Reprezentacije> Reprezentacijes { get; set; }
        public virtual DbSet<Stanovnici> Stanovnicis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Tecajevi> Tecajevis { get; set; }
        public virtual DbSet<tm_Tasks> tm_Tasks { get; set; }
        public virtual DbSet<Uloge> Uloges { get; set; }
        public virtual DbSet<Utakmouse> Utakmice { get; set; }
        public virtual DbSet<Valute> Valutes { get; set; }
    }
}
