//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StanovniciHrvatske
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecajevi
    {
        public int IdValute1 { get; set; }
        public int IdValute2 { get; set; }
        public double Vrijednost { get; set; }
    
        public virtual Valute Valute { get; set; }
        public virtual Valute Valute1 { get; set; }
    }
}
