//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StanovniciHrvatske
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmouse
    {
        public int Id { get; set; }
        public int IdReprezentacije1 { get; set; }
        public int IdReprezentacije2 { get; set; }
        public int Golovi1 { get; set; }
        public int Golovi2 { get; set; }
    
        public virtual Reprezentacije Reprezentacije { get; set; }
        public virtual Reprezentacije Reprezentacije1 { get; set; }
    }
}
